### ISSUE TITLE
Digiromania authentication

### ISSUE THREAD

**Issue by crisp2u** [cralin/plugin.video.DigiOnline.ro#22]
Hi, any plans to implement digiromania login like [here](https://github.com/dexterke/plugin.video.digi.ro-online/blob/7c9a90de45d23148cfaae801226036ecc58b89b0/default.py#L38) ?

At this moment I'm using @dexterke plugin but after reading both repos issues I understand that you guys decided to maintain only this one.

**Comment by rapi3** [comment]
why ?
what would it be used for ?

**Comment by crisp2u** [comment]
I don't have a digionline account but i'm using the digiromania account to login ands have access. I've explained this already in this [issue](https://github.com/dexterke/plugin.video.digi.ro-online/issues/2#issuecomment-503974099)

**Comment by cralin** [comment]
Hi,

As of today, the information about agreement with @dexterke to maintain only this add-on is false/incorrect. There is no (and never was) such agreement.

Maybe I'm missing something here, but what would be the added benefit for introducing in this add-on the support for authentication with digiromania.ro account ?

If you already have a digiromania account then you already have access to the customer portal and as soon as you're on the customer portal it's just a matter of enabling the dedicated account for digionline.ro and then type in the add-on the credentials for that dedicated account. 

Having a user account for accessing online services which is different than the user account for accessing the customer portal is always a good idea since you'd not be exposing yourself to the risks of loosing access to the customer portal because of possible defects/errors/bugs in an add-on written by a third party.

**Comment by cralin** [comment]
> I've explained this already in this [issue](https://github.com/dexterke/plugin.video.digi.ro-online/issues/2#issuecomment-503974099)

This [issue](https://github.com/dexterke/plugin.video.digi.ro-online/issues/2#issuecomment-503974099) was raised against the addon from @dexterke  and, as far as I can see, it was addressed/fixed in the addon from @dexterke.

My last question still stands: 
What would be the added benefit benefit **for this add-on** to introduce the support for authentication with digiromania.ro account ?

**Comment by crisp2u** [comment]
I was not aware that I can simply activate the digionline account from digiromania. I know I can maintain the list of devices from there. Anyway, it seems that we will go on with 2 addons, and you don't want to implement it. That's fine. My mistake, I thought since the platform supports it, it makes sense
